path:
  home: /opt/filebeat
  config: /etc/filebeat
  data: ${path.home}
  logs: ${path.home}/logs/

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/www/html/storage/logs/messagesbus/*/*/*/*.log
      - /var/www/html/storage/logs/laravel-*.log
      - /var/www/html/storage/logs/laravel.log
      - /var/www/html/storage/logs/lumen-*.log
      - /var/www/html/storage/logs/lumen.log
    multiline.type: pattern
    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after
    fields:
      type_log: mozart-ors

logging.metrics.enabled: false

output.file:
  path: "/tmp/filebeat"
  filename: filebeat

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

filebeat.config.modules:
  reload.enabled: false
  path: ${path.home}/modules.d/*.yml
